version: "3"

# Networking
networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

# Docker Services
services:
  # Apache HTTPD project.
  httpd:
    build:
      context: ./docker/httpd
      args:
        - SCORPION_HTTPD_VERSION=${SCORPION_HTTPD_VERSION}
    restart: always
    networks:
      - backend
    ports:
      - 8080:80
