name: Composer Test

on:
  push:
  pull_request:

jobs:
  build-httpd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          set -eux
          cp .env.example .env
          docker-compose build
          docker-compose up -d --no-deps
          docker-compose down
